Remove source update in build script

diff --git a/.github/workflows/linux-new.yml b/.github/workflows/linux-new.yml
--- a/.github/workflows/linux-new.yml
+++ b/.github/workflows/linux-new.yml
@@ -233,22 +233,23 @@ jobs:
 
           # NOTE: to build these binaries on your machine, just use dixyes/prepared-lwmbs:{$matrix['imageTag']} image
 
-          echo "::group::Prepare source"
-          # prepare source for specified php version
-          # you may select only libraries and extensions you will use
-          php /lwmbs/fetch_source.php \
-              "" \
-              "" \
-              --phpVer={$matrix['phpVer']} \
-              --versionFile=/versionFile
-          ret="\$?"
-          echo "::endgroup::"
+          # cached in github actions
+          # echo "::group::Prepare source"
+          # # prepare source for specified php version
+          # # you may select only libraries and extensions you will use
+          # php /lwmbs/fetch_source.php \
+          #     "" \
+          #     "" \
+          #     --phpVer={$matrix['phpVer']} \
+          #     --versionFile=/versionFile
+          # ret="\$?"
+          # echo "::endgroup::"
 
-          if [ ! "\$ret" = "0" ]
-          then
-              echo "::error::fetch source failed"
-              exit 1
-          fi
+          # if [ ! "\$ret" = "0" ]
+          # then
+          #     echo "::error::fetch source failed"
+          #     exit 1
+          # fi
 
           echo "::group::Show versions"
           cat /versionFile
