Update workflows

diff --git a/.github/workflows/macos-new.yml b/.github/workflows/macos-new.yml
--- a/.github/workflows/macos-new.yml
+++ b/.github/workflows/macos-new.yml
@@ -119,3 +119,350 @@ jobs:
           # $json = json_encode(json_decode($jsonDebug, true));
           # file_put_contents(getenv('GITHUB_OUTPUT'), "jobs=$json");
 
+  build:
+    name: ${{ matrix.phpVer }} ${{ matrix.arch }} ${{ toJson(matrix.flavors) }}
+    runs-on: macos-latest
+    needs:
+      - gen-jobs
+    strategy:
+      max-parallel: 3
+      fail-fast: false
+      matrix:
+        include: ${{ fromJson(needs.gen-jobs.outputs.jobs) }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Restore sources
+        uses: actions/cache/restore@v3
+        id: cache-restore
+        with:
+          path: |
+            ~/Library/Caches/Homebrew
+            build/downloads
+            build/src
+            build/versionFile
+          key: ${{ runner.os }}-build-v1-${{ hashFiles('/versionFile') }}
+          restore-keys: |
+            ${{ runner.os }}-build-v1-
+
+      - name: Prepare tools and sources
+        id: prepare
+        run: |
+          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+
+          mkdir -p build
+          cd build
+
+          brew install bison re2c automake autoconf
+          brew link automake
+          echo "PATH=/usr/local/opt/bison/bin:$PATH" >> "$GITHUB_ENV"
+
+          php ../fetch_source.php \
+            "" \
+            "" \
+            "--phpVer=${{ matrix.phpVer }}" \
+            "--versionFile=./versionFile"
+
+          matched_key="${{ steps.cache-restore.outputs.cache-matched-key }}"
+          src_hash="$(sha256sum ./versionFile | head -c 64)"
+          if [ "$matched_key" != "${matched_key##*${src_hash}}" ]
+          then
+            echo "srcHash=" >> "$GITHUB_OUTPUT"
+          else
+            echo "srcHash=${src_hash}" >> "$GITHUB_OUTPUT"
+          fi
+
+      - name: Save sources
+        uses: actions/cache/save@v3
+        if: steps.prepare.outputs.srcHash != ''
+        with:
+          path: |
+            ~/Library/Caches/Homebrew
+            build/downloads
+            build/src
+            build/versionFile
+          key: ${{ runner.os }}-build-v1-${{ steps.prepare.outputs.srcHash }}
+
+      - name: Make build commands
+        shell: php {0}
+        run: |
+          <?php
+
+          $matrix = <<<'EOF'
+          ${{ toJson(matrix) }}
+          EOF;
+
+          $matrix = json_decode($matrix, true);
+          $customLibraries = $matrix['customLibraries'];
+          $customExtensions = $matrix['customExtensions'];
+
+          $commands = [];
+
+          $output = fopen('/tmp/build.sh', 'w');
+
+          $writesh = function (...$args) use ($output) {
+              fwrite($output, sprintf(...$args));
+              fwrite(STDOUT, sprintf(...$args));
+          };
+
+          $writesh(<<<BASH
+          #!/bin/sh
+
+          #set -x
+
+          # cached in github actions
+          # echo "::group::Prepare source"
+          # # prepare source for specified php version
+          # # you may select only libraries and extensions you will use
+          # php ../fetch_source.php \
+          #     "" \
+          #     "" \
+          #     --phpVer={$matrix['phpVer']} \
+          #     --versionFile=./versionFile
+          # ret="\$?"
+          # echo "::endgroup::"
+
+          # if [ ! "\$ret" = "0" ]
+          # then
+          #     echo "::error::fetch source failed"
+          #     exit 1
+          # fi
+
+          echo "::group::Show versions"
+          cat ./versionFile
+          sha256sum ./versionFile
+          echo "::endgroup::"
+
+          BASH);
+
+          $maxLibraries = 'zstd,libssh2,curl,zlib,brotli,libffi,openssl,libzip,bzip2,nghttp2,onig,libyaml,xz,libxml2';
+          $maxExtensions = 'iconv,dom,xml,simplexml,xmlwriter,xmlreader,opcache,bcmath,pdo,phar,mysqlnd,mysqli,pdo,pdo_mysql,mbstring,mbregex,session,ctype,fileinfo,filter,tokenizer,curl,ffi,swow,redis,sockets,openssl,zip,zlib,bz2,yaml,zstd,posix,pcntl,sysvshm,sysvsem,sysvmsg';
+
+          foreach ($matrix['flavors'] as $flavor) {
+              $libraries = match ($flavor) {
+                  'min' => 'libffi',
+                  'lite' => 'zstd,zlib,libffi,libzip,bzip2,xz,onig',
+                  'max', 'max-swow' => $maxLibraries,
+                  'max-libev' => "{$maxLibraries},libev",
+                  'max-swoole' => "{$maxLibraries},libstdc++",
+                  'custom' => $customLibraries,
+              };
+              $extensions = match ($flavor) {
+                  'min' => 'posix,pcntl,ffi,filter,tokenizer,ctype',
+                  'lite' => 'opcache,posix,pcntl,ffi,filter,tokenizer,ctype,iconv,mbstring,mbregex,sockets,zip,zstd,zlib,bz2,phar,fileinfo',
+                  'max' => $maxExtensions,
+                  'max-swow' => "{$maxExtensions},swow",
+                  'max-swoole' => "{$maxExtensions},swoole",
+                  'max-libev' => "{$maxExtensions},libev",
+                  'custom' => $customExtensions,
+              };
+
+              $writesh("\n\n");
+              $writesh(<<<BASH
+              # ----- "$flavor" flavor -----
+
+              echo "::group::Build $flavor libs"
+              # rebuild libs for this flavor to avoid cache
+              php ../build_libs.php \
+                  "$libraries" \
+                  "--arch={$matrix['arch']}" \
+                  "--fresh"
+              ret="\$?"
+              echo "::endgroup::"
+
+              if [ ! "\$ret" = "0" ]
+              then
+                  echo "::error::failed build lib for $flavor"
+              else
+              BASH);
+              foreach ($matrix['sapis'] as $sapi) {
+                  $command = match ($sapi) {
+                      'micro' => 'build_micro.php',
+                      'micro-cli' => 'build_micro.php --fakeCli',
+                      'cli' => 'build_cli.php',
+                  };
+
+                  $targetBin = match ($sapi) {
+                      'micro' => './src/php-src/sapi/micro/micro.sfx',
+                      'micro-cli' => './src/php-src/sapi/micro/micro.sfx',
+                      'cli' => './src/php-src/sapi/cli/php',
+                  };
+                  $binName = match ($sapi) {
+                      'micro' => "micro.sfx",
+                      'micro-cli' => "micro_cli.sfx",
+                      'cli' => "php",
+                  };
+
+                  // $writesh("\n");
+                  // $writesh("# cleam php build dir\n");
+
+                  $writesh("\n\n");
+                  $writesh(<<<BASH
+                      echo "::group::Build $flavor $sapi"
+                      # $sapi
+                      php ../$command \
+                          "$libraries" \
+                          "$extensions" \
+                          "--arch={$matrix['arch']}"
+                      ret="\$?"
+                      echo "::endgroup::"
+                      if [ ! "\$ret" = "0" ]
+                      then
+                          echo "::error::failed build $flavor $sapi"
+                      else
+                          # copy the built bin out
+                          mkdir -p ./out/{$flavor}
+                          cp $targetBin ./out/{$flavor}/$binName
+                          cp $targetBin.debug ./out/{$flavor}/$binName.debug
+                      fi
+                  BASH);
+              }
+              $writesh("\n\n");
+              $writesh(<<<BASH
+                  echo "::group::Dump $flavor licenses"
+                  # dump licenses
+                  php ../dump_licenses.php \
+                      "./out/{$flavor}/licenses" \
+                      "$libraries" \
+                      "$extensions"
+                  # copy versionFile
+                  cp ./versionFile "./out/{$flavor}/versionFile"
+                  echo "::endgroup::"
+
+              fi
+              BASH);
+          }
+
+          $writesh("\n");
+
+      - name: Build
+        shell: sh {0}
+        working-directory: build
+        run: |
+          set +e
+          . /tmp/build.sh
+          # mkdir -p ./out/min
+          # touch ./out/min/micro.sfx
+          # php ../dump_licenses.php \
+          #   "./out/min/licenses" \
+          #   "libffi" \
+          #   "ffi"
+          # cp ./versionFile "./out/min/versionFile"
+
+      - name: Setup node
+        if: always()
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+
+      - name: Prepare node for artifact upload
+        if: always()
+        shell: sh {0}
+        run: |
+          npm i -g @actions/artifact @actions/core @actions/github
+          echo "NODE_PATH=$(npm root --quiet -g)" >> "$GITHUB_ENV"
+
+      - name: Expose GitHub Runtime
+        if: always()
+        uses: crazy-max/ghaction-github-runtime@v2
+
+      - name: Upload artifacts
+        if: always()
+        shell: node {0}
+        run: |
+          const fs = require('fs/promises');
+          const crypto = require('crypto');
+
+          const core = require('@actions/core');
+          // const github = require('@actions/github');
+          const artifact = require('@actions/artifact');
+
+          const matrix = JSON.parse(`
+          ${{ toJson(matrix) }}
+          `)
+
+          const sapis = matrix.sapis
+          const flavors = matrix.flavors
+          const binFile = {
+            'micro': 'micro.sfx',
+            'micro-cli': 'micro_cli.sfx',
+            'cli': 'php',
+          }
+
+          async function main() {
+            let client = artifact.create()
+
+            let artifacts = {};
+            let results = {};
+
+            let versionFile = await fs.readFile('build/versionFile');
+            let srcHash = crypto.createHash('sha256').update(versionFile).digest('hex');
+
+            for (const flavor of flavors) {
+              let dir = `build/out/${flavor}`;
+              for (const sapi of sapis) {
+                let binPath = `${dir}/${binFile[sapi]}`;
+                try {
+                  await fs.access(binPath)
+                  console.log(`\x1b[37m;File ${binPath} found\x1b[0m;`)
+                  let artifactName = `${sapi}_${flavor}_${matrix.phpVer}_${matrix.arch}_${srcHash}`;
+                  artifacts[artifactName] = {
+                    'file': binPath,
+                    'dir': dir,
+                  };
+                  let shaSum = crypto.createHash('sha256').update(await fs.readFile(binPath)).digest('hex')
+                  console.log(`\x1b[37m;File ${binPath} sha256: ${shaSum}\x1b[0m;`)
+                  await fs.writeFile(`${dir}/sha256sums.txt`, `${shaSum}  ${binFile[sapi]}\n`, { flag: 'a' })
+                  try {
+                    shaSum = crypto.createHash('sha256').update(await fs.readFile(`${binPath}.debug`)).digest('hex')
+                    console.log(`\x1b[37m;File ${binPath}.debug sha256: ${shaSum}\x1b[0m;`)
+                    await fs.writeFile(`${dir}/sha256sums.txt`, `${shaSum}  ${binFile[sapi]}.debug\n`, { flag: 'a' })
+                  } catch (error) {
+                    // pass
+                  }
+                } catch (error) {
+                  console.log(`\x1b[30m;File ${binPath} not found\x1b[0m;`)
+                }
+              }
+            }
+
+            for (const [name, info] of Object.entries(artifacts)) {
+              let fileList = [
+                `${info.dir}/sha256sums.txt`,
+                info.file,
+              ];
+              try {
+                await fs.access(`${info.file}.debug`);
+                fileList.push(`${info.file}.debug`);
+              } catch (error) {
+                // pass
+              }
+              try {
+                for (const file of await fs.readdir(`${info.dir}/licenses`)) {
+                  fileList.push(`${info.dir}/licenses/${file}`);
+                }
+              } catch (error) {
+                console.log(`Directory ${info.dir}/licenses not found`);
+              }
+              fileList.push(`${info.dir}/versionFile`);
+
+              try {
+                console.log(`Uploading artifact ${name}`);
+                let uploadResponse = client.uploadArtifact(name, fileList, info.dir);
+                results[name] = uploadResponse;
+              } catch (error) {
+                core.setFailed(error.message);
+              }
+            }
+
+            for (const [name, result] of Object.entries(results)) {
+              let res = await result;
+              console.log(`Artifact ${name} uploaded: ${res.artifactName}`);
+            }
+          }
+
+          main().catch(err => core.setFailed(err.message));
+
+
+
